// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// 2024-02-28 16:31:57.722992 -0500 EST m=+0.000664792

package templates

import "embed"

//go:embed supported_templates/*
var templateFS embed.FS

var templateFSRoot string = "supported_templates"

var SupportedTemplates = []string{
	"go",
	"python",
	"rust",
}
