// Code generated by go generate; DO NOT EDIT.
//This file was generated at
// 2023-08-24 14:37:02.986425 -0400 EDT m=+0.001165876

package templates

import "embed"

//go:embed supported_templates/*
var templateFS embed.FS

var templateFSRoot string = "supported_templates"

var SupportedTemplates = map[string][]string{
	"go": {
		"default",
		"http",
	},
	"python": {
		"default",
	},
	"rust": {
		"default",
	},
}
